
baseurl: /
languageCode: en-us
title: Safe Yelli's blog
theme: "bigspring-light"
googleAnalytics: 'G-SC10M5SL96'
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
  

 
menu:
  main:
    - name: Why?
      url: /why
      weight: 1
    - name: Visit the map or report
      url: https://safeyelli.in
      weight: 2
    - name: Contact Us
      url: /contact/
      weight: 3
    

  footer_left:
      - name: Contact Us
        url: /contact/
  footer_middle:
      - name: Follow our Twitter
        url: https://twitter.com/SafeYelli
      - name: Read the work in progress documentation at our Github
        url: https://github.com/rungdung/harassment-in-yelli
      - name: Instagram
        url: https://instagram.com/safeyelli
    
  
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Mapping Harassment in Yelahanka
  favicon: "/images/faviconLogo.ico"
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo: "images/logo.svg"
  logo_width: "100px"
  navigation_button:
      enable: false
      label: "Report Incident"
      link: "/report"
  variables:
    primary_color: "#FFD815"
    text_color: "#555"
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
