[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.74.3'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_VERSION = "0.89.2"
HUGO_ENV = 'production'


[[redirects]]
  from = "https://safeyelli.netlify.app/*"
  to = "https://safeyelli.in/"
  status = 301
  force = true