[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.98.0'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_VERSION = "0.98.0"
HUGO_ENV = 'production'


[context."blog"]
command = "hugo --baseURL='https://blog.safeyelli.in'" 


[[redirects]]
  from = "https://safeyelli.netlify.app/*"
  to = "https://safeyelli.in/"
  status = 301
  force = true