---
title: "Documenting Street Harassment in Bengaluru"
description: A citizen centric tool to report street harassment, assault and other crimes in Bengaluru. See our community's citizen reported crime data on a map.
draft: no
banner:
  title: Documenting Street Harassment in Bengaluru
  content: "_**A citizen centric tool to report harassment, assault and other crimes on the streets in Bengaluru. See our community's citizen reported crime data on a map.**_ \n \n ಬೆಂಗಳೂರು ಗರವಾಸಿಗಳಿಗೆ  ಇಲ್ಲಿ ನಡೆಯುವ ದೌರ್ಜನ್ಯ ಮತ್ತು ಕಿರುಕುಳವನ್ನು ರಿಪೋರ್ಟ್ ಮಾಡುವ ಉಪಕರಣ. ಇಲ್ಲಿ ಸಂಗ್ರಹವಾದ ಅಪರಾಧ ವರದಿಗಳನ್ನು ನಕ್ಷೆಯ ಮೇಲೆ ಕಾಣಬಹುದು "
  button:
    enable: yes
    label: Report / ಘಟನೆಯನ್ನು ರಿಪೋರ್ಟ್ ಮಾಡಿ
    link: report
text:
- title: Why?
  content: "> **\"If you see something, do something\"**\n\nIf you see sexual assault,
    harassment or catcalling happen to someone else or if something happens to you,
    go to the police and file a report. Additionally, take 5 minutes and fill out
    this form so that you can contribute to a larger cause with your story.\n\n> **“Because
    it’s on you to always do the right thing”**\n\nIf you are being harassed, there
    are certain steps you can take to stop them. If you don’t report it, they’re just
    going to keep doing it. You now have the power to do something about it. Every
    report helps us paint a more comprehensive picture, essentially mapping these
    crimes in order to influence policing and public policy.  \n\n> **\"Because If
    you don't do anything about it, you become complicit\"**\n\nAs socially responsible
    human beings, it is our duty to do everything we can to make sure that the world
    is a safer place today than it was yesterday. Seems far fetched? Well, Let's start
    with making our immediate surroundings safe. Let's strive towards a society where
    a woman can walk down the street without fear of harassment! \n"
- title: ' Defining harassment and other terms'
  content: "(The law provides a clear enough definition of assault)\n\n1.  Assault:
    Whoever assaults or uses criminal force to any woman(or man\\*), intending to
    outrage or knowing it to be likely that he will thereby outrage her modesty (Sec
    creates a hostile or offensive environment.\n\nSection 506 IPC - criminal intimidation.
    (Reverse the gender roles and it still constitutes harassment. Women can also
    be reported under 506 - Criminal intimidation)\\\n\nEven though there is no 'catcalling'
    or 'eve teasing' law in India. People often use Sec 294 IPC in cases relating
    to such offences\n\n3.  Obscene acts and songs.---Whoever, to the annoyance of
    others---\n \n    (a) does any obscene act in any public place, or\n\n    (b)
    sings, recites or utters any obscene song, ballad or words, in or near any public
    place\n 354 IPC).\n\n2.  Harassment:  Sexual harassment is unwanted behaviour of a sexual
    nature which: violates your dignity. makes you feel intimidated, degraded or humiliated."
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 

library(tidyverse) 
library(dplyr)

library(sf)
library(leaflet)
library(leaflet.extras)

library(htmltools)
library(crosstalk)

library(lubridate)
library(DT)

library(osmdata)
library(osmplotr)
library(viridis)

```

```{r reading data, include=FALSE}
# Imports data from multiple spreadsheets and performs operations to uniformize field names
oldData <- read_csv('../resources/reports/allUshahidiResponses.csv') 
newData <- read_csv('../resources/reports/latestReports.csv') 

# Post verification
# If human verified is 'yes'
newData <- newData %>% filter(`human verified`== 'yes')
# If published on Ushahidi (safeyelli.ushahidi.io)
oldData <- oldData %>% filter(`Post Status` == 'published')


# Match field names in the old sheet to new
oldData <-oldData %>% rename( description = `Describe the incident in detail`,
                   `kind of incident` = `What kind of incident was this?`,
                   `date and time` = `When and at what time this happen?`,
                   `gender of victim` = `What is your gender?`,
                   `environmental factors` = `What was wrong with the space?` 
                   )

# Combine data and time in the new sheet
newData$`time of incident` <- format(as_datetime(newData$`time of incident`), format = "%H:%M") 

# Combine data and time in the new sheet
                                    

# Force IST time to UTC time for storage and operations. 
# UTC is recommended, all time must be stored as UTC, need to modify google sheets?
# lubridate as_datetime returns nothing here
newData$`date and time` <- paste(newData$`date of incident`, newData$`time of incident`) %>% 
  as.POSIXct() %>%  force_tzs(tzones = "Asia/Kolkata", tzone_out = "UTC")

oldData$`date and time` <- oldData$`date and time` %>%force_tzs(tzones = "Asia/Kolkata", tzone_out = "UTC")

# Split the location field into lat and lng
newData <- newData %>% separate( col = `location`, into = c("Location.lat", "Location.lon"), sep = "\\,") 

# Old data coords into chr for compatibility
newData <- newData %>% 
  mutate(Location.lat = as.double(Location.lat),
         Location.lon = as.double(Location.lon))

# Map tiles from mapbox
mapUrl="https://api.mapbox.com/styles/v1/rungdung/clciq2jqu000515nyp3fyh54v/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicnVuZ2R1bmciLCJhIjoiY2tqeWh6cXF4MDgzMjJvbWVmbGQzYjAwMyJ9.U-aJyoqyKvTXlhVk43jV1A"

darkMapUrl= "https://api.mapbox.com/styles/v1/rungdung/cl3jusid0001g15odcz3f1dcb/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicnVuZ2R1bmciLCJhIjoiY2tqeWh6cXF4MDgzMjJvbWVmbGQzYjAwMyJ9.U-aJyoqyKvTXlhVk43jV1A"
```



```{r merging dataframes and creating sf frames, include=FALSE}
# combine dataframes for leaflet 
allData <- bind_rows(oldData, newData)
allData <- rename(allData, lat=Location.lat, lng = Location.lon)




```

```{r operations on data, echo=FALSE, message=FALSE, warning=FALSE}
# create unique date and time fields to simplify leaflet


# Attach a coordinate reference 
allData <- allData %>%
  st_as_sf(coords = c('lng', 'lat'),crs = 4326)

allData <- allData %>% 
  mutate(date = as.Date(`date and time`, '%d/%m/%Y'),
         year = as.integer(year(date)),
         month = as.character(month(date)),
         hour = as.integer(format(as_datetime(allData$`date and time`, tz="Asia/Kolkata"), 
                           format="%H"))
         )

allData <- allData %>% 
  arrange(`date and time`) %>% 
  rowid_to_column(var="rowID")

allDataFilter <- allData %>%  
  separate('kind of incident', paste("Category", 1:5, sep="_"), sep=",") %>% 
  pivot_longer(cols=`Category_1`:`Category_5`,
               values_to = "kind of incident") %>% 
  drop_na(`kind of incident`) 
```

```{r Formatting popup text, message=FALSE, warning=FALSE, include=FALSE}
# create popup text for the leaflet map, all formatting is done in html


  allData$popupText <-
  paste0(
    '<strong>',
    allData$`kind of incident`,
    '</strong> <br/> <br/>',
    format(allData$`date and time`, tz="Asia/Kolkata"),
    '<br/> <br/>',
    allData$`description`,
    ' '
  ) %>%
  lapply(htmltools::HTML)
```

```{r Creating shared data frame for crosstalk, echo=FALSE, message=FALSE, warning=FALSE}
# sharedData is the format for crosstalk. Crosstalk enables filters by sharing dataframes on a static site.
sharedD <- SharedData$new(allData, ~rowID, group="map")
sharedDFilter <- SharedData$new(allDataFilter, ~rowID, group="map")
```

```{r get Street Lamp Data, echo=FALSE, message=FALSE, warning=FALSE}
bboxC <- c(77.557125, 13.095279, 77.589719, 13.110556)

bbox <- osmplotr::get_bbox(bboxC)

# Data from OSM
# streetlights from OSM
dat_streetLamps <-
  extract_osm_objects (
    key = "highway",
    value = "street_lamp",
    return_type = 'point',
    bbox = bbox
  )

colourLeg <- colorFactor(viridis(8), dat_streetLamps$status)
```

```{r Mappinnng!, echo=FALSE, message=FALSE, warning=FALSE}

#leaflet object
#addProviderTiles(providers$CartoDB.Positron) not working
map <- leaflet(sharedD, height = "100vh") %>%
  enableTileCaching() %>%
  addTiles(urlTemplate = darkMapUrl,
           attribution =  'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
           group = "Street Lamps",
           options = tileOptions(useCache = TRUE, crossOrigin = TRUE)) %>%
  addTiles(urlTemplate = mapUrl,
           attribution =  'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
           group = "Default",
           options = tileOptions(useCache = TRUE, crossOrigin = TRUE)) %>%
  
  fitBounds(77.439880,12.850618,77.765350,13.124871) %>%
  setMaxBounds(77.071139,12.707331,78.114153,13.228584) %>%
  addScaleBar() %>%
  
  addCircleMarkers(
    popup = paste(allData$popupText),
    radius = 4,
    opacity = 0.8,
    color = '#be0915',
    popupOptions = popupOptions(maxWidth = 400),
    #clusterOptions = clusterOptions(),
    group = "Incidents",
  ) %>%
  
  # OSM data on main map
  addCircleMarkers(
    data = dat_streetLamps,
    opacity = 0.5,
    color = ~ colourLeg(dat_streetLamps$status),
    radius = 2,
    label = ~ htmlEscape(dat_streetLamps$status),
    group = "Street Lamps"
  ) %>%
  addLegend(
    position = "bottomright",
    pal = colourLeg,
    values = ~ dat_streetLamps$status,
    title = "Status of mapped streetlights",
    group = "Street Lamps"
  ) %>%
  
  addWebGLHeatmap(
    intensity = 1,
    size = "100",
    units="px",
    opacity=0.5,
    group = "Heat Map"
  ) %>% 
  
  addLayersControl(
    baseGroups = c("default"),
    overlayGroups = c("Heat Map", "Incidents", "Street Lamps"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>% 
  
  hideGroup("Street Lamps") %>% 
  
  addControlGPS() %>% 
  activateGPS() %>% 
  addSearchOSM()


```

```{r formatting output,echo=FALSE, message=FALSE, warning=FALSE, out.width='100%'}


# filters
yearFilter <- filter_slider("Year", "Year", sharedD, column= ~year, step=1, width="100%")
timeOfDayFilter <- filter_slider("Hour","Time of Day (24H format)", sharedD,  column=~hour, step=1, width="100%")



# map display
tags$div(
  class = "map-section",
  #dateFilter,
  tags$div(class = "crosstalk-map",
           map),
  tags$div(class = "crosstalk-filters  col-md-11",
           tags$h4('Map filters:'),
           list(
             tags$div(
               class = "row",
               tags$div(class = "col-md-6",
                        yearFilter),
               tags$div(class = "col-md-6",
                        timeOfDayFilter)
             ),
             tags$div(class = "row",
                      tags$div(class = "col-md-12",
                               filter_checkbox("Incident type", "Type", sharedDFilter, group= ~`kind of incident`, inline=TRUE)),
                    )
                    
           )),
  
)
```



    

