---
title: "Why do we map infrastruture?"
description: ""
draft: false

####################### Banner #########################
banner:
  title : "Why do we map infrastructure?"
  content : | 
    ### Map of Streetlights mapped so far. 
    Hover to see the status of each streetlight. Mapping of status in progress"


  button:
    enable : false
    label : "Report / ಘಟನೆಯನ್ನು ರಿಪೋರ್ಟ್ ಮಾಡಿ"
    link : "report" 

##################### Text-after #######################
map: true
text:
  -
    title: 
    content: |
      Safe Yelli? has been conducting expeditions around Yelahanka to map public infrastructure in the area. We call it ***"Community Mapping"*** and *have been focused on mapping shops, street vendors, parks, conditions of street lights etc.* The idea behind this is to **encourage accountability in public policies** by curating **data about our infrastructural conditions and making it publicly available.**

      From 11th April '22, we opened this up as a volunteer based community exercise by organizing small walks in the neighbourhood on pleasant summer evenings. We would go around SFS mapping things like local landmarks, conditions of street lights, popular food joints etc. We encouraged everyone to bring a friend along to make it an even more fun experience.
      
      These evening walks have been quiet fruitful. In just 4-5 days we had mapped 30+ streets. We hope to spread across Bengaluru and make a detailed map of spaces beyond SFS colony and contribute to making Bengaluru safer for everyone.
  -
    title: 
    content: |
      ## DIY mapping 
      ### Create an Account
      Go to [www.openstreetmap.org](https://www.openstreetmap.org) and create an account. 
      
      ### Download
      
      Download [OSM GO, interestingly named as 'Mapping less frustrating](https://play.google.com/store/apps/details?id=fr.dogeo.osmgo) because most other mobile mapping applications are complex to start off with. 
      
      Once downloaded, log in to Open Street Maps through the menu inside the app
      
      ### Walk around
      - Make sure your GPS seems to be accurate. 
      - Ensure callibration using relative measurements on the ground. Ask yourself if the road corner where you are standing is the same road corner according to the map. 
      - After doing that. Add a street lamp using the application by searching for the 'street_lamp' tag. 
      
      And there you are, you've added a street lamp. Not to OSM yet, there are a few more steps for that. 
      
      ### Add additional tags
      
      What kind of a street lamp is it? Fill the 'type' field.
      
      Is it working? Is it not working? Does it need maintanance? All these information can be added through a custom tag.
        - Click the add button. 
        - Name the tag 'status'.
          - Fill in with either working, not_working or needs_maintanence 
          
      
      ### Upload data
      After mapping a few of the street lamps nearby, click on the cloud upload icon on the home screen of the app.
      - Fill in data such as the area you were mapping.
        for example: One of our changeset comments is "Survey of Street Lamps in Yelahanka New Town as part of safeyelli.in's efforts"
        
      Upload! You have now contributed data to Open Street Maps.
  
      
---
```{r include=FALSE}
library(osmdata)
library(osmplotr)
library(leaflet)
library(leaflet.extras)
library(htmltools)
library(viridis)
library(htmltools)
library(rgdal)
library(tidyverse)
```

```{r message=FALSE, warning=FALSE, include=FALSE}

# the Bounding Box of Ylk New Town that we have mapped streetlights, shops in.
bboxC <- c(77.557125,13.095279,77.589719,13.110556)
bbox <- osmplotr::get_bbox(bboxC)

# Data from OSM
# streetlights from OSM
dat_streetLamps <- extract_osm_objects (key = "highway", value="street_lamp", return_type = 'point', bbox = bbox) 

# shops from OSM 
dat_shops <- extract_osm_objects (key = 'shop', return_type = 'point', bbox = bbox)

# data from street light illumination tracker app

GPX_file <- '../../resources/assets/Community-Mapping/Adhavan_on_5_11_SFS.gpx'
illuminationTrack <- readOGR(GPX_file, verbose = FALSE)

# map tiles from mapbox
mapUrl="https://api.mapbox.com/styles/v1/rungdung/cku6gh76r1dvh17o3zkfllvjz/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicnVuZ2R1bmciLCJhIjoiY2tqeWh6cXF4MDgzMjJvbWVmbGQzYjAwMyJ9.U-aJyoqyKvTXlhVk43jV1A"

darkMapUrl= "https://api.mapbox.com/styles/v1/rungdung/cl3jusid0001g15odcz3f1dcb/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoicnVuZ2R1bmciLCJhIjoiY2tqeWh6cXF4MDgzMjJvbWVmbGQzYjAwMyJ9.U-aJyoqyKvTXlhVk43jV1A"
```

```{r message=FALSE, warning=FALSE, include=FALSE}

cuts <- cut(illuminationTrack$ogr_lux, 
            labels=c("nil", "low", "medium", "directly lit"),
            breaks=c(0, 7, 10, 200, 70000),
            right=FALSE)
illuminationTrack$lightLevel = cuts


pallete <- colorFactor(viridis(4, option = "B"),
                     domain = cuts) 
palleteNum <- colorNumeric(c("brown", "yellow", "green", "blue"),
                     domain = c(0:4))
```


```{r echo=FALSE, message=FALSE, warning=FALSE}


colourLeg <- colorFactor(viridis(8), dat_streetLamps$status)

streetLights <- leaflet(dat_streetLamps, 
                        width="100%", 
                        height="100vh",
                        ) %>%
  addTiles(urlTemplate = darkMapUrl,
           attribution =  'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
           ) %>%
  fitBounds(77.567232,13.097142,77.579978,13.109009) %>%
  setMaxBounds(77.554808, 13.087922, 77.608495, 13.114213) %>% 
  addCircleMarkers(opacity=0.5, 
                   color = ~colourLeg(status), 
                   radius= 2, 
                   label = ~htmlEscape(status), 
                   group = "Locations"
                   ) %>% 
  addHeatmap(lng = illuminationTrack$ogr_lng,
               lat = illuminationTrack$ogr_lat,
               intensity =  cuts,
               radius = 3,
               blur=5,
               group = "Traces",
             max=10,
             cellSize = 1,
             gradient = pallete(cuts)
            ) %>% 

  addLayersControl(
                   overlayGroups = c("Locations", "Traces"),
                   options = layersControlOptions(collapsed = FALSE)
                  ) %>% 
  addLegend(position="bottomright",
            pal = colourLeg,
            values = ~status,
            title="Status of mapped streetlights")

tags$div(class = "map-section",
         streetLights
)
```


