---
title: "Bottus as Metaphors"

description: "What does a Bottu mean to you?"

draft: false
type: blog

author: Saee, Samar, Adhavan
  
banner:
  title: "What does a Bottu mean to you?"
  content: "Developing engagement tools for on-the-ground interactions"
coverImage:
  alt: An image of safe yelli stickers
  url: blogs/stylised-workInProgress-bottu-board.jpeg
---

# The motivation for on-the-ground involvement

SafeYelli has been rethinking and revisiting our motivations. When we look at what we've done so far, the same question surfaces: what tangible outcomes can we show people? Sure, we've delivered cumulative reports to the police. We've documented conditions of streetlights and are trying to actively encourage reporting. But the scale is too small. We are too small a community to represent the data accurately. We need other communities to report too. How do we engage with them?

## Bottu as a metaphor

The Bottu (Pottu, or Bindi) Map is a physical and interactive map of Bangalore, made accessible to the general public. It will visit Metro stations, bus stands, your local park and everywhere that is feasible. You can mark an area where you've been eve-teased, harassed or assaulted with a Bottu. This creates a qualitative map of unsafe regions in and around Bangalore.

This installation **is a physical manifestation of the** SafeYelli website, to document the undocumented feelings, and to shed light on the dark figures of crime.

Bottu Board will unite unheard voices to create a live graph that spreads awareness, particularly about women's safety in public. **The Bottus are a symbol of femininity but they are also an indelible mark. Much like the kind of scar that is left on victims of harrasment. The bottu board represents the unspoken daily experiences of the people we love and care about.**

A QR code to SafeYelli is also present on the board, allowing people to report incidents in detail on the website.

### The pains of designing such a map

We've spent over three weeks making progress on it. Over four people were collaborating at one point, and now we've brought in more people into SafeYelli to work on it.

-   Starting from designing a base map in MapBox, we've tried to come up with a wayfinding experience that does not depend on experience with Google Maps.

    -   How do we simplify data just enough to make sure that users understand the map without feeling overwhelmed? Bengaluru is huge and complex, when you zoom out.

-   We are looking at transit hubs in various areas as wayfinding markers. If one can have a visual hierarchy of transit hubs, (Majestic big, Shivaji nagara slightly smaller and NES even smaller)

-   We are also looking at getting information from the corporation through RTI requests.
