---
title: "Conversations on SafeYelli, colleges and Bottu Board"

description: "Why should we focus on student communities? Why should we not focus on student communities? How are you going to fund yourself?"

draft: false
type: blog

author: 
  - Saee
  - Samar 
  - Adhavan
  
banner:
  title: "Conversations on SafeYelli, colleges and Bottu Board"
  content: "Why should we focus on student communities? Why should we not focus on student communities? How are you going to fund yourself?"
  
coverImage:
  alt: An image of safe yelli stickers
  url: blogs/on-moving-bengaluru.jpeg

---
## Blr Design Week

We were invited to a Bangalore Design Week brainstorming session where students from 10 design schools in Bengaluru were partaking. Art in Transit was kind enough to make that introduction

While talking to students from NID, Ramayyah, RV and so on, there are varying perspectives and experiences we anecdotally hear about. For some, SafeYelli presents as a diary of horrible incidents that they only hear about. Some are aware that some areas around their campuses are where 'incidents like these happen'. And to some, these are simply non-existent threats.

## Bottu Board

The Bottu Board is a physical and interactive map of Bangalore, made accessible to the general public. The board and some bottus (bindis) will be made available for people to mark places that have made them feel unsafe. This creates a qualitative map of unsafe regions in and around Bangalore. The installation also doubles as a 3D representation, created by stacking bottus on top of each other that serves as a live graph. 

This installation also serves the same purpose as the SafeYelli website, to document the undocumented feelings, to shed light on the dark figures of crime.

The Bottu Board will be moved around the city to various places, uniting unheard voices to create a live graph that spreads awareness, particularly about women’s safety in public. The bottus represent femininity - the women around us, the women who made us, the women we love and care about. Thus, it aims to relate to the women who are willing to share their experiences - anonymously if needed - and give them a platform as a collective.

A QR code to SafeYelli is also present on the board, allowing people to report incidents in detail on the website. 

### The pains of designing such a map
We've spent over three weeks making progress on it. Starting from designing a base map in MapBox, we've tried to come up with 
