---
title: "Why should you report?"
subtitle: ""
# meta description
description: "Why should you report?"
draft: false
---


`r blogdown::shortcode_open("faq", "Your reports are anonymous")`
 
At no point are you asked for personally identifiable information.

`r blogdown::shortcode_close("faq")`


`r blogdown::shortcode_open("faq", "Why should you report?")`

> "Because it's on you to always do the right thing"

If you are being harassed, there are certain steps you can take to stop them. If you don't report it, they're just going to keep doing it. You now have the power to do something about it. Every report helps us paint a more comprehensive picture, essentially mapping these crimes in order to influence policing and public policy. 
`r blogdown::shortcode_close("faq")`

`r blogdown::shortcode_open("faq", "How can you help?")`

> **"If you see something, do something"**

If you see sexual assault, harassment or catcalling happen to someone else or if something happens to you, go to the police and file a report. Additionally, take 5 minutes and fill out this form so that you can contribute to a larger cause with your story.
`r blogdown::shortcode_close("faq")`

`r blogdown::shortcode_open("faq", "Why does it matter?")`

> **"Because If you don't do anything about it, you become complicit"**

As socially responsible human beings, it is our duty to do everything we can to make sure that the world is a safer place today than it was yesterday. Seems far fetched? Well, Let's start with making our immediate surroundings safe. Let's strive towards a society where a woman can walk down the street without fear of harassment!
`r blogdown::shortcode_close("faq")`