---
title: "Why are we doing this?"
//date: "19/10/2021"

---
 
We live in a scary place in time to have normalised harassment and catcalling. There seem to be too many stories from victims who happen to be predominantly young students. What could be some causal factors for this?  It is very likely that poorly maintained public infrastructure and inept policing strategies are the major causal factors for crime in our area. But there are deeper roots, what social factors cause these?

Situational crime prevention measures focus on the circumstances in which crime takes place, rather than on offenders. Keeping that in mind, strategies should be constructed limiting the opportunities for people to commit crime. 

**Of the many types of crime that are perpetrated, sexual assault, harassment and catcalling are more pronounced and have impacted a relatively larger demographic of our community.** Fortunately, adopting a proper crime prevention strategy can help curb the intensity and frequency of these crimes. Our objective is to gather enough data to present a credible case and influence effective prevention strategies on the basis of hard numbers.

Individuals with a higher propensity to commit crime might not be pushed over the edge, if we're able to successfully deny them the 'opportunity to commit crime.'

## What is the Dark Figure of crime?

The Dark Figure of crime is defined as the number of crimes not known or recorded by the police.

### How do we know this?

There is a significant difference in the number of crimes reported in police statistics and victim surveys. **Victim surveys tend to be a lot more open and don't require prolonged participation. More often than not, people don't report less serious offences, like catcalling, to the police because:**

1.  They don't know that a particular type of behaviour or action is a crime.

2.  They might be apprehensive of the protracted legal battle that will ensue.

3.  Sometimes, a family member might be the perpetrator.

Some studies by academics in India estimate the dark figure to be about 50 times higher than the official crime rates. It is only prudent to infer that the dark figure in the case of sexual assault and harassment is higher. The only way that we can paint a complete picture is to have multiple, credible and independent surveys that deal with the same specific problem(crime).

Essentially, if you want to feel safer and make your immediate living environment feel comfortable and secure, then the least you can do is report.
